import Config

url = [
  host: System.get_env("DEV_URL_HOST", "localhost"),
  scheme: System.get_env("DEV_URL_SCHEME", "http"),
  port: "DEV_URL_PORT" |> System.get_env("4000") |> String.to_integer()
]

# Configure your database
config :cen, Cen.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "cen_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :cen, CenWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  url: [host: "rabbit.txssu.dev", scheme: "https", port: "443"],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "4jGvHNPsKMkfo+7YsmwzeDF29RdPEE79ghjq9MLTmPlFug6sjhzfohFPiwPRKCGg",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:cen, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:cen, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :cen, CenWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/cen_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

config :cen, :csp, s3: "http://localhost:9000"

# Enable dev routes for dashboard and mailbox
config :cen, dev_routes: true

config :ex_aws,
  json_codec: Jason,
  access_key_id: "cen-storage",
  secret_access_key: "secret1234",
  s3: [
    scheme: "http://",
    host: "localhost",
    port: 9000
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :waffle,
  storage: Waffle.Storage.S3,
  bucket: "cen-dev",
  asset_host: "http://localhost:9000/cen-dev"
